![alt text](image-1.png)

# Задача 1.15. Собственный ортонормированный базис

## Теоретическая часть

**1. Самосопряженный оператор**
Оператор $\phi$ задан симметричной матрицей $A = A^T$. Для таких операторов в вещественном пространстве справедлива **Спектральная теорема**:
* Все собственные значения $\lambda_i$ являются вещественными числами.
* Собственные векторы, соответствующие *различным* собственным значениям, автоматически ортогональны.
* Матрица оператора всегда может быть диагонализирована с помощью ортогональной матрицы перехода $P$ (состоящей из ортонормированных собственных векторов): $P^T A P = \Lambda$, где $\Lambda$ — диагональная матрица собственных значений.

**2. Алгоритм нахождения базиса**
1. Решаем характеристическое уравнение $\det(A - \lambda I) = 0$ для поиска собственных значений $\lambda_i$.
2. Для каждого $\lambda_i$ решаем систему $(A - \lambda_i I)X = 0$ для поиска собственных векторов.
3. Если собственное значение имеет кратность $>1$ (вырожденное собственное подпространство), выбираем в нем базис и ортогонализируем его (например, методом ортогонализации Грама-Шмидта или просто подбирая ортогональные векторы).
4. Нормируем все полученные векторы (делим на их евклидову длину), чтобы получить *ортонормированный* базис.

**3. Матрица в новом базисе**
В базисе из собственных векторов матрица оператора принимает **диагональный вид**, а на главной диагонали стоят соответствующие собственные значения.

In [3]:
import numpy as np

# Задаем матрицу оператора
A = np.array([
    [17, -8,  4],
    [-8, 17, -4],
    [ 4, -4, 11]
])

print("Исходная матрица A:")
print(A)
print("-" * 40)

# Используем функцию eigh (Eigenvalues Hermitian)
# Она специально предназначена для симметричных/эрмитовых матриц 
# и гарантирует возврат ортонормированных собственных векторов
eigenvalues, eigenvectors = np.linalg.eigh(A)

print("Собственные значения (диагональ новой матрицы):")
print(np.round(eigenvalues, 4))
print("-" * 40)

print("Ортонормированный базис (столбцы матрицы перехода P):")
print(np.round(eigenvectors, 4))
print("-" * 40)

# Формируем матрицу в новом базисе (должна быть диагональной)
# P^T * A * P = Lambda
P = eigenvectors
Lambda = P.T @ A @ P
Lambda_clean = Lambda.copy()
Lambda_clean[np.abs(Lambda_clean) < 1e-10] = 0.0
print("Матрица оператора в новом ортонормированном базисе:")
print(Lambda_clean)

Исходная матрица A:
[[17 -8  4]
 [-8 17 -4]
 [ 4 -4 11]]
----------------------------------------
Собственные значения (диагональ новой матрицы):
[ 9.  9. 27.]
----------------------------------------
Ортонормированный базис (столбцы матрицы перехода P):
[[ 0.7327 -0.1365 -0.6667]
 [ 0.6681  0.3304  0.6667]
 [-0.1293  0.9339 -0.3333]]
----------------------------------------
Матрица оператора в новом ортонормированном базисе:
[[ 9.  0.  0.]
 [ 0.  9.  0.]
 [ 0.  0. 27.]]
