---

# Задача 1.20. Эквивалентность квадратичных форм

## Условие

Эквивалентны ли над полем вещественных чисел квадратичные формы $Q_1$ и $Q_2$, где
$$Q_1 = 2x_1^2 + 9x_2^2 + 3x_3^2 + 8x_1x_2 - 4x_1x_3 - 10x_2x_3;$$
$$Q_2 = 2x_1^2 + 3x_2^2 + 6x_3^2 - 4x_1x_2 - 4x_1x_3 + 8x_2x_3.$$


## Теоретическая часть

### 1. Эквивалентность квадратичных форм

Определение. Две квадратичные формы $Q_1$ и $Q_2$ называются эквивалентными над полем $\mathbb{F}$, если существует невырожденное линейное преобразование $x = Cy$ ($\det C \neq 0$), переводящее одну форму в другую: $Q_1(x) = Q_2(Cy)$.

В матричной форме: $A_1 = C^T A_2 C$, где $A_1, A_2$ — матрицы форм, $C$ — невырожденная матрица.


### 2. Закон инерции Сильвестра

**Теорема (Закон инерции Сильвестра).** При любом приведении квадратичной формы к каноническому (диагональному) виду число положительных и число отрицательных коэффициентов остаётся неизменным. Эта пара чисел $(n_+, n_-)$ называется **сигнатурой** формы.

**Следствие.** Две квадратичные формы над полем $\mathbb{R}$ эквивалентны тогда и только тогда, когда они имеют **одинаковую сигнатуру** (одинаковое число положительных и отрицательных квадратов в каноническом виде).

**Почему это работает?** Любая вещественная симметричная матрица диагонализуема ортогональным преобразованием (спектральная теорема). Собственные значения матрицы квадратичной формы определяют знаки коэффициентов в каноническом виде. Поскольку ортогональное преобразование невырождено, сигнатура является инвариантом формы относительно невырожденных замен переменных.

### 3. Алгоритм проверки

1. Составить симметричные матрицы $A_1$ и $A_2$ обеих форм.
2. Найти собственные значения каждой матрицы (они вещественны, так как матрицы симметричны).
3. Посчитать сигнатуры $(n_+, n_-, n_0)$ — количество положительных, отрицательных и нулевых собственных значений.
4. Если сигнатуры совпадают — формы эквивалентны; иначе — нет.

## Решение

### Шаг 1. Матрицы квадратичных форм

$$A_1 = \begin{pmatrix} 2 & 4 & -2 \\ 4 & 9 & -5 \\ -2 & -5 & 3 \end{pmatrix}, \qquad A_2 = \begin{pmatrix} 2 & -2 & -2 \\ -2 & 3 & 4 \\ -2 & 4 & 6 \end{pmatrix}$$

### Шаг 2. Находим собственные значения и сигнатуры

In [1]:
import numpy as np
import sympy as sp

# Матрицы квадратичных форм
A1 = np.array([
    [ 2,  4, -2],
    [ 4,  9, -5],
    [-2, -5,  3]
], dtype=float)

A2 = np.array([
    [ 2, -2, -2],
    [-2,  3,  4],
    [-2,  4,  6]
], dtype=float)

print("Матрица A₁ формы Q₁:")
print(A1.astype(int))
print("\nМатрица A₂ формы Q₂:")
print(A2.astype(int))

# === ХАРАКТЕРИСТИЧЕСКИЕ ПОЛИНОМЫ (символьные вычисления через SymPy) ===
#
# Характеристический полином матрицы A — это многочлен от λ:
#     p(λ) = det(A - λ·I)
# где I — единичная матрица.
#
# Корни этого полинома (где p(λ) = 0) — это собственные значения матрицы A.
# Мы считаем полином символьно, чтобы увидеть его явный вид (для красоты в отчёте),
# но сами корни находим численно через NumPy — это быстрее и точнее.

lam = sp.Symbol('lambda')                          # создаём символ λ (не число, а переменная)

# Формируем матрицу (A - λ·I):
#   sp.eye(3) — единичная матрица 3×3 (как число 1, но для матриц)
#   lam * sp.eye(3) — это λ·I = diag(λ, λ, λ)
#   sp.Matrix(A1) - lam*sp.eye(3) — вычитаем из A1
#   .det() — считаем определитель этой матрицы → получаем многочлен от λ
char_poly1 = (sp.Matrix(A1) - lam*sp.eye(3)).det()
char_poly2 = (sp.Matrix(A2) - lam*sp.eye(3)).det()

# sp.expand() раскрывает скобки, чтобы полином был в стандартном виде
# (например, превращает (λ-1)(λ-2) в λ² - 3λ + 2)
print("\nQ₁:")
print(f"Характеристический полином: {sp.expand(char_poly1)}")

# === СОБСТВЕННЫЕ ЗНАЧЕНИЯ (численные вычисления через NumPy) ===
#
# np.linalg.eigvalsh(A) находит собственные значения симметричной матрицы A.
# Почему именно eigvalsh, а не eig?
#   - eigvalsh работает ТОЛЬКО с симметричными матрицами (а матрица квадратичной
#     формы всегда симметрична по определению)
#   - он быстрее и надёжнее: не выдаст комплексные числа из-за погрешностей
#   - возвращает только значения (без векторов) — нам векторы не нужны
eig1 = np.linalg.eigvalsh(A1)

# np.sort() сортирует по возрастанию, [::-1] разворачивает → получаем по убыванию
eig1_sorted = np.sort(eig1)[::-1]
print(f"Собственные значения A₁: {eig1_sorted}")

# === ПОДСЧЁТ СИГНАТУРЫ (n₊, n₋, n₀) ===
#
# Почему сравниваем с 1e-10, а не с 0?
#   Компьютер работает с числами с плавающей точкой, и "ноль" может оказаться
#   чем-то вроде 0.0000000001 или -0.0000000001 из-за погрешностей вычислений.
#   Поэтому считаем:
#     - положительным то, что БОЛЬШЕ +10⁻¹⁰
#     - отрицательным то, что МЕНЬШЕ -10⁻¹⁰
#     - нулевым всё, что лежит в интервале [-10⁻¹⁰, +10⁻¹⁰]

n_pos1 = int(np.sum(eig1 > 1e-10))      # количество положительных λ
n_neg1 = int(np.sum(eig1 < -1e-10))     # количество отрицательных λ
n_zero1 = 3 - n_pos1 - n_neg1           # остальные — нулевые (всего 3 значения)
sig1 = (n_pos1, n_neg1, n_zero1)        # сигнатура = тройка (n₊, n₋, n₀)
print(f"Сигнатура Q₁: (n₊={n_pos1}, n₋={n_neg1}, n₀={n_zero1})")

print("\nQ₂:")
print(f"Характеристический полином: {sp.expand(char_poly2)}")
eig2 = np.linalg.eigvalsh(A2)
eig2_sorted = np.sort(eig2)[::-1]
print(f"Собственные значения A₂: {eig2_sorted}")

n_pos2 = int(np.sum(eig2 > 1e-10))
n_neg2 = int(np.sum(eig2 < -1e-10))
n_zero2 = 3 - n_pos2 - n_neg2
sig2 = (n_pos2, n_neg2, n_zero2)
print(f"Сигнатура Q₂: (n₊={n_pos2}, n₋={n_neg2}, n₀={n_zero2})")

# === СРАВНЕНИЕ СИГНАТУР ===
# По закону инерции Сильвестра: формы эквивалентны ⟺ сигнатуры совпадают
print(f"\nСигнатуры совпадают: {sig1} == {sig2}")
if sig1 == sig2:
    print("Формы Q₁ и Q₂ ЭКВИВАЛЕНТНЫ над полем ℝ (по закону инерции Сильвестра).")
else:
    print("Формы Q₁ и Q₂ НЕ эквивалентны.")

Матрица A₁ формы Q₁:
[[ 2  4 -2]
 [ 4  9 -5]
 [-2 -5  3]]

Матрица A₂ формы Q₂:
[[ 2 -2 -2]
 [-2  3  4]
 [-2  4  6]]

Q₁:
Характеристический полином: -lambda**3 + 14.0*lambda**2 - 6.0*lambda
Собственные значения A₁: [ 1.35574385e+01  4.42561476e-01 -1.91443056e-16]
Сигнатура Q₁: (n₊=2, n₋=0, n₀=1)

Q₂:
Характеристический полином: -lambda**3 + 11.0*lambda**2 - 12.0*lambda
Собственные значения A₂: [9.77200187e+00 1.22799813e+00 1.32913689e-15]
Сигнатура Q₂: (n₊=2, n₋=0, n₀=1)

Сигнатуры совпадают: (2, 0, 1) == (2, 0, 1)
Формы Q₁ и Q₂ ЭКВИВАЛЕНТНЫ над полем ℝ (по закону инерции Сильвестра).
